name: Build with CMake and Clang on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.30.x'

    - name: Prepare Directory
      run: |
        mkdir build
        cd build

    - name: Build project
      run: cmake ..

    - name: Make
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: bin/endstone_stone_shuffle.dll
